### PR TITLE
Update member profile

### PR DESCRIPTION
**Pull request by GraceSevillano**

### CODE REVIEW

**Comment by GraceSevillano** [comment]
Updated member profile:
- Added a new profile image
- Updated personal data in `_data/members.yml`
- @maintainer_username Please review this member profile update

**Comment by AntoineAndre** [comment]
Why the `Gemfile.lock` file has changed?

**Comment by GraceSevillano** [comment]
I've already returned it to its previous state

**Comment by fkanehiro** [comment]
A small change remains in `Gemfile.lock`.

**Pull request merged**
