### PR TITLE
Add Japanese localization

### PR DESCRIPTION
**Pull request by gergondet**
Note: the PR is massive due to the files' reorganization and might slow down your browser

As requested in #70 this follows the same pattern as 70 this follows the same pattern as done in mc_rtc

I have done some ChatGPT powered translations for some of the content, please check the following files and feel free to correct them:
- `_i18n/jp.yml`
- `_data/members.yml` (two `bio-jp` for the example, one `research-jp` and all `name-jp` although those should be correct)
- `_i18n/jp/index-overview.html`

Please also translate the following pages:
- `_i18n/jp/contact.html`
- `_i18n/jp/join_us.html`

Changes related to localization:
- a member can have a name-jp entry that will be used to display on the members' list (I have filled it up for every current member that has their name listed on the current Japanese website)
- a member can have a bio-jp and research-jp entry that will be used when generating their Japanese page (otherwise the English version is displayed on the Japanese website)
- news are read from the `_i18n/en.yml` and `_i18n/jp.yml`, to add a news one simply needs to add entries into the `news` list there
- same for members that are also part of the "Humanoid Lab" structure, the list is taken from the localization file and should be updated on both sides

Once this is ready to merge, I will need to have a look at the deploy script since the structure is a little different

### CODE REVIEW

**Comment by fkanehiro** [comment]
@gergondet 
You work fast as usual!
I'm trying to test this PR but when I execute `bundle exec jekyll server --trace --safe`, I got the following error.
```
 Liquid Exception: Liquid syntax error (line 8): Unknown tag 't' in 404.html
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
```
Do you know how to fix this?

**Comment by gergondet** [comment]
I think you need to get rid of the `--safe` option

Also note that the website has no index.html generated so when you open `http://localhost:4000` you will have to pick the en or jp folder (that's not a problem for the real site because we will redirect anyway)

**Comment by fkanehiro** [comment]
When I get rid of the `--safe` option, I got the following error.
```
  Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
```
I am using jekyll 3.9.3.

**Comment by gergondet** [comment]
Can you copy the full stack?

Usually this happens because a translation is missing and that will be reported earlier in the stack.

> I am using jekyll 3.9.3.

I was using 3.9.0 but I updated and I couldn't reproduce the issue.

**Comment by fkanehiro** [comment]
```
kanehiro@MacBookAir2020 jrl-umi3218.github.com % bundle exec jekyll server --trace
Configuration file: /Users/kanehiro/src/jrl-umi3218.github.com/_config.yml
            Source: /Users/kanehiro/src/jrl-umi3218.github.com
       Destination: /Users/kanehiro/src/jrl-umi3218.github.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Building site for language: "en" to: /Users/kanehiro/src/jrl-umi3218.github.com/_site/en
Loading translation from file /Users/kanehiro/src/jrl-umi3218.github.com/_i18n/en.yml
Missing i18n key: en:CNRS-AIST JRL
Using translation '' from default language: en
  Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
TypeError: no implicit conversion of nil into String
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:632:in `initialize'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:632:in `initialize'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:649:in `new'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:649:in `translate'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:406:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/block.rb:17:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/tags/capture.rb:26:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
  /Library/Ruby/Gems/2.6.0/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:126:in `render_liquid'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:195:in `render_layout'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:158:in `place_in_layouts'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:88:in `render_document'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/site.rb:472:in `block in render_pages'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `each'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `render_pages'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/site.rb:192:in `render'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:185:in `block in process'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:171:in `each'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.8.0/lib/jekyll-multiple-languages-plugin.rb:171:in `process'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `block in start'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `each'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `start'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /Library/Ruby/Gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Library/Ruby/Gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Library/Ruby/Gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
kanehiro@MacBookAir2020 jrl-umi3218.github.com % 
```

**Comment by gergondet** [comment]
Do you have an untracked page with `title: CNRS-AIST JRL`? If so, this should be removed (not the page, just the title)

**Comment by fkanehiro** [comment]
Yes, I have several untracked pages and the issue was solved by editing them.
Thank you!

**Comment by fkanehiro** [comment]
@gergondet 
Can you please merge my commits in `add_jp_translation` branch into this PR?

**Comment by rohanpsingh** [comment]
Thanks @gergondet for creating this PR. I had this on my to-do list since a long time but I never got it :disappointed: 

We currently have a manually created Japanese lang page for "Humanoid lab" [here](https://unit.aist.go.jp/jrl-22022/en/humanoid_lab_jp.html). Will this PR remove that file?

**Comment by fkanehiro** [comment]
>Can you please merge my commits in add_jp_translation branch into this PR?

The commits seem to be included in PR #129.

**Comment by gergondet** [comment]
> The commits seem to be included in PR https://github.com/jrl-umi3218/jrl-umi3218.github.com/pull/129.

I have added them onto this branch.

> Okay I realized, it does remove that file.

The Japanese translation of this page is generated by the same mechanism as the other pages so the file is not required anymore.

@rohanpsingh the update in [`8fe2a59` (#128)](https://github.com/jrl-umi3218/jrl-umi3218.github.com/pull/128/commits/8fe2a5961b5d84df67b711fa1fd5e81efc9ddfd4) is only partial. You need to update the list in the `_i18n/jp.yml` file as well.

**Comment by rohanpsingh** [comment]
> the update in [8fe2a59 (#128)](https://github.com/jrl-umi3218/jrl-umi3218.github.com/pull/128/commits/8fe2a5961b5d84df67b711fa1fd5e81efc9ddfd4) is only partial. You need to update the list in the _i18n/jp.yml file as well.

I know that and that's why the PR was a draft! :smile: 
I need to ask someone to help me translate.

**Comment by rohanpsingh** [comment]
@gergondet I finished making my changes (if there are any suggestion from @fkanehiro san about HumanoidLab page I can incorporate them in another PR)

**Comment by gergondet** [comment]
@fkanehiro is that ok for you? If so I will look into adapting the deploy script and merge this.

**Comment by fkanehiro** [comment]
Ok for me.
I have some small modifications but I can create a PR for these later.

**Comment by fkanehiro** [comment]
http://jrl-umi3218.github.io/ ->  https://unit.aist.go.jp/jrl-22022/en/index.html -> Not Found
https://unit.aist.go.jp/jrl-22022 -> old Japanese website

**Comment by gergondet** [comment]
> http://jrl-umi3218.github.io/ -> [unit.aist.go.jp/jrl-22022/en/index.html](https://unit.aist.go.jp/jrl-22022/en/index.html) -> Not Found

This is working now (I didn't change anything right but it did disappear a few minutes while I was working some details out so maybe you tried at a wrong time?)

> [unit.aist.go.jp/jrl-22022](https://unit.aist.go.jp/jrl-22022) -> old Japanese website

I wasn't sure about this one. I though we had to keep it as-is to match the AIST style but I can setup a redirect to `jp/index.html`

**Comment by fkanehiro** [comment]
>I wasn't sure about this one. I though we had to keep it as-is to match the AIST style but I can setup a redirect to jp/index.html

It is ok to have our own style.
Please setup the redirect.

**Comment by gergondet** [comment]
> Please setup the redirect.

Ok, https://unit.aist.go.jp/jrl-22022 now goes to the website in this repo

**Comment by fkanehiro** [comment]
Thank you @gergondet !

**Pull request merged**
